name: "Netatmo Favorites Weather Stations"
description: "your Netatmo Favorites Weather Stations and even more!"
version: "0.9.7.6"
slug: "nfws"
init: false
url: "https://github.com/DevLn/GiZMoSK1221-hass-addons"
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
options:
  netatmo:
    client_id: ""
    client_secret: ""
    refresh_interval: 2
    oauth_code: ""
  nfws:
      deleteRetain: false
      log_level: "debug"
schema:
  netatmo:
    client_id: "str?"
    client_secret: "str?"
    refresh_interval: "int(1,)"
    oauth_code: "str?"
    show_response: bool?
  nfws:
    deleteRetain: bool     
    log_level: "list(debug|info|warning|error|critical)"
services:
  - mqtt:need
image: "ghcr.io/devln/{arch}-addon-nfws"
