# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages:
    wattsonic: !include wattsonic.yaml
    #wattsonic_db: !include wattsonic_sql_mariadb.yaml
    #wattsonic_db: !include wattsonic_sql_postgre.yaml
